const Quotes=[
{author:' Rumi',
quote:"The heart knows a hundred thousand ways to speak."},
{author:'~John Lennon',
quote:"Life is what happens when you're busy making other plans."},
{author:'~Robert Frost',
quote:"In three words I can sum up everything I've learned about life: it goes on." },
{author:'~Confucius',
quote:"Life is really simple, but we insist on making it complicated."},
{author:'~Charles R. Swindoll',
quote:"Life is 10% what happens to us and 90% how we react to it."},
{author:' ~Helen Keller' ,
quote:"Life is either a daring adventure or nothing at all."},
{author:'~Albert Einstein',
quote:"Life is like riding a bicycle. To keep your balance, you must keep moving."},
{author:'~Sarah Louise Delany',
quote:"Life is short, and it is up to you to make it sweet." },
{author:'~Sholom Aleichem',
quote:"Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor." },
{author:'~Lao Tzu',
quote:"Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like." },
{author:'~Grandma Moses',
quote:"Life is what we make it, always has been, always will be."},
{author:'~David Wilkerson',
quote:"~Love is not just something you feel, it is something you do."},
{author:'Unknown',
quote:"Love is an endless act of forgiveness. Forgiveness is the key to action and freedom."},
{author:'~Maya Angelou',
quote:"Love is composed of a single soul inhabiting two bodies." },
{author:'~Audrey Hepburn',
quote:"The best thing to hold onto in life is each other."},
{author:'~Paulo Coelho',
quote:"Love is an untamed force. When we try to control it, it destroys us. When we try to imprison it, it enslaves us. When we try to understand it, it leaves us feeling lost and confused."},
{author:'~Nicholas Sparks ',
quote:"Love is like the wind, you can't see it but you can feel it." },
{author:'~Robert A. Heinlein',
quote:"Love is that condition in which the happiness of another person is essential to your own."},
{author:'~John Lennon',
quote:"Love is the flower you've got to let grow."},
{author:'~William Blake',
quote:"Love is an act of endless forgiveness. Forgiveness is the key to action and freedom." },
{author:'~Mahatma Gandhi',
quote:"Love is the strongest force the world possesses and yet it is the humblest imaginable."},
{author:'~Steve Jobs',
quote:"The only way to do great work is to love what you do."},
{author:'~Theodore Roosevelt',
quote:"Believe you can and you're halfway there."},
{author:'~Winston Churchill',
quote:"Success is not final, failure is not fatal: It is the courage to continue that counts."},
{author:'~Eleanor Roosevelt',
quote:"The future belongs to those who believe in the beauty of their dreams."},
{author:' ~Wayne Gretzky',
quote:"You miss 100% of the shots you don't take."},
{author:' ~Sam Levenson',
quote:"Don't watch the clock; do what it does. Keep going."},
{author:'~Franklin D. Roosevelt',
quote:"The only limit to our realization of tomorrow will be our doubts of today."},
{author:' ~Unknown',
quote:"The harder you work for something, the greater you'll feel when you achieve it."},
{author:'~C.S. Lewis',
quote:"You are never too old to set another goal or to dream a new dream."},
{author:'~Ralph Waldo Emerson',
quote:"The only person you are destined to become is the person you decide to be."},
{author:'~Stephen R. Covey',
quote:"Trust is the glue of life. It's the most essential ingredient in effective communication. It's the foundational principle that holds all relationships."},
{author:'Unknown',
quote:"Trust takes years to build, seconds to break, and forever to repair." },
{author:' ~George MacDonald',
quote:"To be trusted is a greater compliment than being loved." },
{author:' ~William P. Young',
quote:"Trust is the fruit of a relationship in which you know you are loved."},
{author:'~Ronald Reagan',
quote:"Trust, but verify."},
{author:'~Benjamin Spock',
quote:"Trust yourself. You know more than you think you do." },
{author:' ~Warren Buffett',
quote:"It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently." },
{author:'~Ernest Hemingway',
quote:"The best way to find out if you can trust somebody is to trust them."},
{author:'~Walter Anderson',
quote:"Trust is like a vase. Once it's broken, though you can fix it, the vase will never be the same again." },
{author:'~Claudia Black',
quote:"Trust in yourself. Your perceptions are often far more accurate than you are willing to believe." },
{author:'~Paulo Coelho',
quote:"Tears are words that need to be written."},
{author:'~ Carl Jung',
quote:"The word 'happiness' would lose its meaning if it were not balanced by sadness."},
{author:'~Tupac Shakur',
quote:"Behind every sweet smile, there is a bitter sadness that no one can ever see and feel."},
{author:'~Chuck Palahniuk',
quote:"The only way to find true happiness is to risk being completely cut open."},
{author:'~Terry Pratchett',
quote:"Sometimes you laugh because you've got no more room for crying."},
{author:'~Henry Rollins',
quote:"It's sad when someone you know becomes someone you knew."},
{author:'~Khalil Gibran',
quote:"Sadness is but a wall between two gardens."},
{author:'~Jonathan Safran Foer',
quote:"You cannot protect yourself from sadness without protecting yourself from happiness." },
{author:'~Unknown',
quote:"The saddest thing in the world is loving someone who used to love you."},
{author:'~Dr. Seuss',
quote:"Don't cry because it's over, smile because it happened."},
{author:'~Marilyn Monroe',
quote:"Sometimes good things fall apart so better things can fall together." },
{author:'~Jerry Seinfeld',
quote:"Breaking up is like knocking over a Coke machine. You can't do it in one push. You gotta rock it back and forth a few times, and then it goes over." },
{author:'~Dr. Seuss',
quote:"Don't cry because it's over, smile because it happened." },
{author:'~Haruki Murakami',
quote:"Pain is inevitable. Suffering is optional."},
{author:'~Chuck Palahniuk',
quote:"It's so hard to forget pain, but it's even harder to remember sweetness. We have no scar to show for happiness." },
{author:'~Socrates',
quote:"The hottest love has the coldest end."},
{author:'~ Steve Maraboli',
quote:"Letting go means to come to the realization that some people are a part of your history, but not a part of your destiny."},
{author:'~John Green',
quote:"You can love someone so much, but you can never love people as much as you can miss them."},
{author:'~Sonya Parker',
quote:"The wrong person will never give you what you want, but they'll make sure they get what they want from you."},
{author:'~Alexander Graham Bell',
quote:"When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us."},
{author:' ~C.S. Lewis',
quote:"Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one!'"},
{author:' ~Elbert Hubbard',
quote:"A friend is someone who knows all about you and still loves you."},
{author:'~Woodrow Wilson',
quote:"Friendship is the only cement that will ever hold the world together."},
{author:' ~C.S. Lewis',
quote:"Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one!'"},
{author:'~Walter Winchell',
quote:"A real friend is one who walks in when the rest of the world walks out." },
{author:'~C.S. Lewis',
quote:"Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one!'"},
{author:'~Elbert Hubbard',
quote:"A friend is someone who knows all about you and still loves you."},
{author:'~Woodrow Wilson',
quote:"Friendship is the only cement that will ever hold the world together."},
{author:'~Ralph Waldo Emerson',
quote:"A true friend is somebody who can make you feel better no matter how bad things may be."},
{author:'~C.S. Lewis',
quote:"Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one!'"},
{author:'~Helen Keller',
quote:"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart." },
{author:' ~Blaise Pascal',
quote:"The heart has its reasons of which reason knows nothing."},
{author:'~Lao Tzu',
quote:"Love is of all passions the strongest, for it attacks simultaneously the head, the heart, and the senses."},
{author:'~Jesus Christ',
quote:"Do not let your hearts be troubled. Trust in God; trust also in me."},
{author:'~Oscar Wilde',
quote:"The heart was made to be broken." },
{author:'~Confucius',
quote:"Wherever you go, go with all your heart."},
{author:'~Woody Allen',
quote:"The heart wants what it wants. There's no logic to these things. You meet someone and you fall in love and that's that."},
{author:' ~Alfred Adler',
quote:"Follow your heart, but take your brain with you."},
{author:'~Michael Ondaatje',
quote:"The heart is an organ of fire."}
];

// accessing the html elements using DOM
const Quotedisplay = document.getElementById('display') 
const Quoteauthor = document.getElementById('author') 
const Bthelement = document.getElementById('getQuote')

//function to generate random quotes
function RandomQuotes(){
    let i=Math.floor(Math.random()*Quotes.length)
    console.log(i);
    Quotedisplay.innerHTML=Quotes[i].quote;
    Quoteauthor.innerHTML=Quotes[i].author;
    console.log(i)
}
Bthelement.addEventListener('click',RandomQuotes)